name: CI

on: [push]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - uses: actions/cache@v3
        id: npm-cache
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}-{{ checksum "patches.hash" }}
      - name: Install packages
        run: yarn

  rust-setup:
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
    - name: Checkout the source code
      uses: actions/checkout@v3

    - name: Install & display rust toolchain
      run: |
        rustup show
        rustup component add rust-src

    - name: Check targets are installed correctly
      run: rustup target list --installed

    - name: Cache Crates
      uses: actions/cache@v3
      with:
        path: ~/.cargo
        key: ${{ runner.os }}-rust-${{ hashFiles('rust-toolchain.toml') }}
        restore-keys: |
          ${{ runner.os }}-rust

    - name: Check if cargo-contract exists
      id: check-cargo-contract
      continue-on-error: true
      run: cargo contract --version

    - name: Install cargo contract
      if: ${{ steps.check-cargo-contract.outcome == 'failure' }}
      run: |
        cargo install cargo-dylint dylint-link
        cargo install --force --locked cargo-contract --version 2.2.1


  frontend-build:
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - uses: actions/cache@v3
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - name: Frontend build
        run: yarn frontend:build
        env:
          CI: false

  backend-build:
    runs-on: ubuntu-latest
    needs: [rust-setup]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Restore Cache
        uses: actions/cache@v3
        with:
          path: ~/.cargo
          key: ${{ runner.os }}-rust-${{ hashFiles('rust-toolchain.toml') }}
          restore-keys: |
            ${{ runner.os }}-rust
      - name: NFT SmartContract build by cargo contract
        run: yarn build:nft
      - name: Content SmartContract build by cargo contract
        run: yarn build:content
      - name: All SmartContract build by swanky
        run: yarn compile:all

  